[workspace]
resolver = "2"
members = [
	"Conformance",
	"Sources/TuringMachine",
	"Sources/WebAssembly/*",
	"IR/*",
	"Targets/Json",
	"Targets/Luau/*",
	"Targets/LuaJIT/*",
	"CLI"
]

[workspace.dependencies]
list = { git = "https://github.com/SovereignSatellite/RustListDataStructure.git", rev = "a236bf9" }
set = { git = "https://github.com/SovereignSatellite/RustSetDataStructure.git", rev = "b82ef8c" }

cranelift-isle = { version = "0.124.1", default-features = false }

hashbrown = { version = "0.16.0", default-features = false, features = [
	"default-hasher",
	"equivalent",
	"inline-more",
] }

wasmparser = { version = "0.235.0", default-features = false }
