[package]
name = "control-flow-builder"
version = "1.0.0"
edition = "2021"

[dependencies]
control-flow-graph = { path = "../Graph" }
control-flow-structurer = { path = "../Structurer" }

list.workspace = true
set.workspace = true
wasmparser.workspace = true
