[package]
name = "luau-builder"
version = "1.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
hashbrown.workspace = true
ir-graph.workspace = true
parking_lot.workspace = true
turing-machine-foreign.workspace = true
web-assembly-foreign.workspace = true

luau-tree = { path = "../Tree" }
