[package]
name = "luau-builder"
version = "1.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
hashbrown.workspace = true
ir-graph.workspace = true
luau-foreign.workspace = true
parking_lot.workspace = true
stacker.workspace = true

ir-allocator = { path = "../../../IR/Allocator" }
luau-tree = { path = "../Tree" }
