[package]
name = "luajit-builder"
version = "1.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
ir-graph = { path = "../../../IR/Graph" }
luajit-tree = { path = "../Tree" }
turing-machine-foreign = { path = "../../../Sources/TuringMachine/Foreign" }
web-assembly-foreign = { path = "../../../Sources/WebAssembly/Foreign" }

hashbrown.workspace = true
parking_lot.workspace = true
