[package]
name = "luajit-builder"
version = "1.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
ir-graph = { path = "../../../IR/Graph" }
luajit-tree = { path = "../Tree" }
turing-machine-source = { path = "../../../Sources/TuringMachine" }
web-assembly-lifter = { path = "../../../Sources/WebAssembly/Lifter" }

hashbrown.workspace = true
parking_lot.workspace = true
