[package]
name = "luajit-printer"
version = "1.0.0"
edition = "2024"

[dependencies]
web-assembly-lifter = { path = "../../../Sources/WebAssembly/Lifter" }
ir-graph = { path = "../../../IR/Graph" }
ir-visitor = { path = "../../../IR/Visitor" }
luajit-tree = { path = "../Tree" }
luajit-builder = { path = "../Builder" }

clap.workspace = true
hashbrown.workspace = true
wasmparser = { workspace = true, features = ["validate"] }

[[bin]]
name = "wasm2luajit"
path = "src/main.rs"
