[package]
name = "spider-cli"
version = "1.0.0"
edition = "2024"

[dependencies]
ir-graph.workspace = true
ir-pipeline.workspace = true
luajit-builder.workspace = true
luajit-printer.workspace = true
luau-builder.workspace = true
luau-printer.workspace = true
parking_lot.workspace = true
web-assembly-lifter.workspace = true

json-target = { path = "../Targets/Json" }
luajit-tree = { path = "../Targets/LuaJIT/Tree" }
luau-tree = { path = "../Targets/Luau/Tree" }
turing-machine-lifter = { path = "../Sources/TuringMachine/Lifter" }

clap = { version = "=4.6.1", default-features = false, features = [
	"color",
	"derive",
	"error-context",
	"help",
	"std",
	"suggestions",
	"usage",
] }

wasmparser = { workspace = true, features = ["validate"] }
