[package]
name = "spider-cli"
version = "1.0.0"
edition = "2024"

[dependencies]
ir-graph.workspace = true
parking_lot.workspace = true

ir-pipeline = { path = "../IR/Pipeline" }
json-target = { path = "../Targets/Json" }
luajit-builder = { path = "../Targets/LuaJIT/Builder" }
luajit-printer = { path = "../Targets/LuaJIT/Printer" }
luajit-tree = { path = "../Targets/LuaJIT/Tree" }
luau-builder = { path = "../Targets/Luau/Builder" }
luau-printer = { path = "../Targets/Luau/Printer" }
luau-tree = { path = "../Targets/Luau/Tree" }
turing-machine-lifter = { path = "../Sources/TuringMachine/Lifter" }
web-assembly-lifter = { path = "../Sources/WebAssembly/Lifter" }

clap = { version = "=4.6.1", default-features = false, features = [
	"color",
	"derive",
	"error-context",
	"help",
	"std",
	"suggestions",
	"usage",
] }

wasmparser = { workspace = true, features = ["validate"] }
