[package]
name = "conformance"
version = "1.0.0"
edition = "2024"

[lints]
workspace = true

[dev-dependencies]
ir-graph.workspace = true
parking_lot.workspace = true

datatest-stable = "=0.3.3"
wast = "=247.0.0"

ir-pipeline = { path = "../IR/Pipeline" }
luajit-builder = { path = "../Targets/LuaJIT/Builder" }
luajit-printer = { path = "../Targets/LuaJIT/Printer" }
luau-builder = { path = "../Targets/Luau/Builder" }
luau-printer = { path = "../Targets/Luau/Printer" }
web-assembly-lifter = { path = "../Sources/WebAssembly/Lifter" }

[[test]]
name = "luau"
harness = false

[[test]]
name = "luajit"
harness = false
