[package]
name = "conformance"
version = "1.0.0"
edition = "2024"

[lints]
workspace = true

[dev-dependencies]
ir-graph.workspace = true
ir-pipeline.workspace = true
luajit-builder.workspace = true
luajit-lower.workspace = true
luajit-printer.workspace = true
luau-builder.workspace = true
luau-lower.workspace = true
luau-printer.workspace = true
parking_lot.workspace = true
web-assembly-lifter.workspace = true

datatest-stable = "=0.3.3"
wast = "=247.0.0"

[[test]]
name = "luau"
harness = false

[[test]]
name = "luajit"
harness = false
