-- SECTION bit32_and
local bit32_and = bit32.band

-- SECTION bit32_or
local bit32_or = bit32.bor

-- SECTION bit32_xor
local bit32_xor = bit32.bxor

-- SECTION bit32_lshift
local bit32_lshift = bit32.lshift

-- SECTION bit32_rshift
local bit32_rshift = bit32.rshift

-- SECTION bit32_arshift
local bit32_arshift = bit32.arshift

-- SECTION bit32_lrotate
local bit32_lrotate = bit32.lrotate

-- SECTION bit32_rrotate
local bit32_rrotate = bit32.rrotate
