[package]
name = "luau-printer"
version = "1.0.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
web-assembly-lifter = { path = "../../../Sources/WebAssembly/Lifter" }
ir-graph = { path = "../../../IR/Graph" }
ir-visitor = { path = "../../../IR/Visitor" }
luau-tree = { path = "../Tree" }
luau-builder = { path = "../Builder" }

hashbrown.workspace = true
