[package]
name = "data-flow-graph"
version = "1.0.0"
edition = "2021"

[dependencies]
control-flow-graph = { path = "../../Control Flow/Graph" }
list = { git = "https://github.com/Rerumu/List.git", rev = "57d0ca8" }
