name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_release:
    name: Release - ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - name: Windows x64
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - name: macOS ARM64
            os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          submodules: recursive

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5
        with:
          key: ${{ matrix.target }}

      - name: Build
        run: cargo build --target ${{ matrix.target }} --release --verbose

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          if [ "${{ runner.os }}" = "Windows" ]; then
            EXT=".exe"
          else
            EXT=""
          fi

          cp "target/${{ matrix.target }}/release/wasm2luau${EXT}" "artifacts/wasm2luau-${{ matrix.target }}${EXT}"

      - name: Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
        with:
          files: artifacts/*
          fail_on_unmatched_files: true
